CREATE TYPE "public"."good_type" AS ENUM('Gottheit', 'Erzdämon');--> statement-breakpoint
CREATE TABLE "gods" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "gods_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"aspects" varchar(255)[],
	"holy_symbol" varchar(255),
	"secondName" varchar(255)
);
