CREATE TABLE "experience_levels" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "experience_levels_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"startingAP" integer NOT NULL,
	"attributeMax" integer NOT NULL,
	"skillMax" integer NOT NULL,
	"combatSkillMax" integer NOT NULL,
	"attributeSumMax" integer NOT NULL,
	"maxSpells" integer NOT NULL,
	"maxForeignSpells" integer NOT NULL
);
