CREATE TABLE "races" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "races_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"LE" integer NOT NULL,
	"SK" integer NOT NULL,
	"ZK" integer NOT NULL,
	"GS" integer NOT NULL,
	"attribute" text NOT NULL,
	"advantages" text[],
	"disadvantages" text[],
	"apCost" integer NOT NULL
);
