CREATE TABLE "talents" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "talents_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"use" text[],
	"newApplication" text[],
	"category" text NOT NULL,
	"check" text[],
	"description" text NOT NULL,
	"applications" text[],
	"encumbrance" boolean,
	"tools" text,
	"quality" text NOT NULL,
	"failedCheck" text NOT NULL,
	"criticalSuccess" text NOT NULL,
	"botch" text NOT NULL,
	"improvementCost" text NOT NULL
);
