CREATE TABLE "general_special_abilities" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "general_special_abilities_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"description" text NOT NULL,
	"rules" text NOT NULL,
	"apValue" integer NOT NULL,
	"dynamicApText" text,
	"category" varchar(100),
	"requirementsText" text,
	"noDisadvantage" text[],
	"combinedTalentsLevel" integer
);
--> statement-breakpoint
CREATE TABLE "special_ability_combined_talent_requirements" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "special_ability_combined_talent_requirements_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"special_ability_id" integer NOT NULL,
	"talent_id" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "special_ability_talent_requirements" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "special_ability_talent_requirements_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"special_ability_id" integer NOT NULL,
	"talent_id" integer NOT NULL,
	"level" integer NOT NULL
);
--> statement-breakpoint
ALTER TABLE "special_ability_combined_talent_requirements" ADD CONSTRAINT "special_ability_combined_talent_requirements_special_ability_id_general_special_abilities_id_fk" FOREIGN KEY ("special_ability_id") REFERENCES "public"."general_special_abilities"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "special_ability_combined_talent_requirements" ADD CONSTRAINT "special_ability_combined_talent_requirements_talent_id_talents_id_fk" FOREIGN KEY ("talent_id") REFERENCES "public"."talents"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "special_ability_talent_requirements" ADD CONSTRAINT "special_ability_talent_requirements_special_ability_id_general_special_abilities_id_fk" FOREIGN KEY ("special_ability_id") REFERENCES "public"."general_special_abilities"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "special_ability_talent_requirements" ADD CONSTRAINT "special_ability_talent_requirements_talent_id_talents_id_fk" FOREIGN KEY ("talent_id") REFERENCES "public"."talents"("id") ON DELETE cascade ON UPDATE no action;