CREATE TABLE "advantages" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "advantages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"description" text NOT NULL,
	"rules" text NOT NULL,
	"range" text,
	"actions" text,
	"requirements" text,
	"apValue" integer NOT NULL,
	"apText" text
);
--> statement-breakpoint
CREATE TABLE "disadvantages" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "disadvantages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"description" text NOT NULL,
	"rules" text NOT NULL,
	"range" text,
	"actions" text,
	"requirements" text,
	"apValue" integer NOT NULL,
	"apText" text
);
