CREATE TABLE "culture_advantages" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "culture_advantages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"culture_id" integer NOT NULL,
	"advantage_id" integer NOT NULL,
	"is_common" boolean DEFAULT true NOT NULL,
	"note" text
);
--> statement-breakpoint
CREATE TABLE "culture_disadvantages" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "culture_disadvantages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"culture_id" integer NOT NULL,
	"disadvantage_id" integer NOT NULL,
	"is_common" boolean DEFAULT true NOT NULL,
	"note" text
);
--> statement-breakpoint
CREATE TABLE "culture_talent_package" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "culture_talent_package_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"culture_id" integer NOT NULL,
	"talent_id" integer NOT NULL,
	"value" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cultures" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cultures_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"description" text NOT NULL,
	"occurrenceAndLifestyle" text,
	"worldViewAndReligion" text,
	"customs" text,
	"garbAndArmaments" text,
	"language" text NOT NULL,
	"script" text,
	"areaKnowledge" text,
	"socialStatus" text[],
	"commonMundaneProfessions" text[],
	"commonMagicProfessions" text[],
	"commonBlessedProfessions" text[],
	"commonSkills" text[],
	"uncommonSkills" text[],
	"commonMaleNames" text[],
	"commonFemaleNames" text[],
	"commonFamilyNames" text[],
	"nobleFamilies" text[],
	"culturePackageApCost" integer
);
--> statement-breakpoint
ALTER TABLE "culture_advantages" ADD CONSTRAINT "culture_advantages_culture_id_cultures_id_fk" FOREIGN KEY ("culture_id") REFERENCES "public"."cultures"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "culture_advantages" ADD CONSTRAINT "culture_advantages_advantage_id_advantages_id_fk" FOREIGN KEY ("advantage_id") REFERENCES "public"."advantages"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "culture_disadvantages" ADD CONSTRAINT "culture_disadvantages_culture_id_cultures_id_fk" FOREIGN KEY ("culture_id") REFERENCES "public"."cultures"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "culture_disadvantages" ADD CONSTRAINT "culture_disadvantages_disadvantage_id_disadvantages_id_fk" FOREIGN KEY ("disadvantage_id") REFERENCES "public"."disadvantages"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "culture_talent_package" ADD CONSTRAINT "culture_talent_package_culture_id_cultures_id_fk" FOREIGN KEY ("culture_id") REFERENCES "public"."cultures"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "culture_talent_package" ADD CONSTRAINT "culture_talent_package_talent_id_talents_id_fk" FOREIGN KEY ("talent_id") REFERENCES "public"."talents"("id") ON DELETE cascade ON UPDATE no action;