CREATE TABLE "combat_special_abilities" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "combat_special_abilities_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"type" varchar(50) NOT NULL,
	"description" text NOT NULL,
	"rules" text NOT NULL,
	"penalty" text,
	"requirementsText" text,
	"combatTechniques" text[],
	"apValue" integer NOT NULL,
	"apText" text
);
