CREATE TABLE "staff_spells" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "staff_spells_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"effect" text NOT NULL,
	"requirements" text,
	"volume" integer NOT NULL,
	"bindingCost" text,
	"property_id" integer,
	"propertyNote" text,
	"apValue" integer NOT NULL,
	"apNote" text
);
--> statement-breakpoint
ALTER TABLE "staff_spells" ADD CONSTRAINT "staff_spells_property_id_magic_properties_id_fk" FOREIGN KEY ("property_id") REFERENCES "public"."magic_properties"("id") ON DELETE set null ON UPDATE no action;