CREATE TABLE "familiar_tricks" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "familiar_tricks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"effect" text NOT NULL,
	"animal_types" text[] NOT NULL,
	"asp_cost" integer NOT NULL,
    "asp_text" text,
	"duration" text NOT NULL,
	"property_id" integer,
	"property_note" text,
	"ap_value" integer NOT NULL,
	"ap_note" text
);
--> statement-breakpoint
CREATE TABLE "witch_curses" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "witch_curses_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"check" text[] NOT NULL,
	"modified_by_zk" integer DEFAULT 0 NOT NULL,
	"modified_by_sk" integer DEFAULT 0 NOT NULL,
	"effect" text NOT NULL,
	"asp_cost" integer NOT NULL,
	"asp_text" text,
	"duration" text NOT NULL,
	"property_id" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "witch_special_abilities" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "witch_special_abilities_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"rules" text NOT NULL,
	"requirements" text,
	"apValue" integer NOT NULL
);
--> statement-breakpoint
ALTER TABLE "familiar_tricks" ADD CONSTRAINT "familiar_tricks_property_id_magic_properties_id_fk" FOREIGN KEY ("property_id") REFERENCES "public"."magic_properties"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "witch_curses" ADD CONSTRAINT "witch_curses_property_id_magic_properties_id_fk" FOREIGN KEY ("property_id") REFERENCES "public"."magic_properties"("id") ON DELETE restrict ON UPDATE no action;