CREATE TABLE "elven_songs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "elven_songs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"check" text[] NOT NULL,
	"effect" text NOT NULL,
	"talent" text NOT NULL,
	"asp_cost" integer NOT NULL,
	"asp_text" text,
	"duration" text NOT NULL,
	"property_id" integer NOT NULL,
	"improvementCost" varchar(1) NOT NULL
);
--> statement-breakpoint
ALTER TABLE "elven_songs" ADD CONSTRAINT "elven_songs_property_id_magic_properties_id_fk" FOREIGN KEY ("property_id") REFERENCES "public"."magic_properties"("id") ON DELETE restrict ON UPDATE no action;