CREATE TABLE "cantrips" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cantrips_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"effect" text NOT NULL,
	"range" text NOT NULL,
	"duration" text NOT NULL,
	"target_category" text NOT NULL,
	"property_id" integer NOT NULL,
	"ap_value" integer NOT NULL
);
--> statement-breakpoint
ALTER TABLE "cantrips" ADD CONSTRAINT "cantrips_property_id_magic_properties_id_fk" FOREIGN KEY ("property_id") REFERENCES "public"."magic_properties"("id") ON DELETE restrict ON UPDATE no action;