CREATE TABLE "spells" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "spells_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"check" text[] NOT NULL,
	"modified_by_zk" integer DEFAULT 0 NOT NULL,
	"modified_by_sk" integer DEFAULT 0 NOT NULL,
	"effect" text NOT NULL,
	"casting_duration" integer NOT NULL,
	"asp_cost" integer NOT NULL,
	"asp_text" text,
	"costs_not_modifiable" integer DEFAULT 0 NOT NULL,
	"range" text NOT NULL,
	"duration" text NOT NULL,
	"target_category" text NOT NULL,
	"property_id" integer NOT NULL,
	"distribution" text[] NOT NULL,
	"improvementCost" varchar(1) NOT NULL
);
--> statement-breakpoint
ALTER TABLE "spells" ADD CONSTRAINT "spells_property_id_magic_properties_id_fk" FOREIGN KEY ("property_id") REFERENCES "public"."magic_properties"("id") ON DELETE restrict ON UPDATE no action;