CREATE TABLE "church_tradition_favorable_talents" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "church_tradition_favorable_talents_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tradition_id" integer NOT NULL,
	"talent_id" integer,
	"note" text
);
--> statement-breakpoint
CREATE TABLE "church_tradition_ranks" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "church_tradition_ranks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tradition_id" integer NOT NULL,
	"rank" varchar(100) NOT NULL,
	"title" varchar(255) NOT NULL,
	"order" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "church_tradition_rules" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "church_tradition_rules_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tradition_id" integer NOT NULL,
	"rule" text NOT NULL,
	"order" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "church_traditions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "church_traditions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"god_id" integer NOT NULL,
	"description" text NOT NULL,
	"leading_attribute" varchar(50) NOT NULL,
	"requirements" text,
	"ap_value" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "moral_codex_entries" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "moral_codex_entries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tradition_id" integer NOT NULL,
	"name" varchar(255) NOT NULL,
	"description" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "church_tradition_favorable_talents" ADD CONSTRAINT "church_tradition_favorable_talents_tradition_id_church_traditions_id_fk" FOREIGN KEY ("tradition_id") REFERENCES "public"."church_traditions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "church_tradition_favorable_talents" ADD CONSTRAINT "church_tradition_favorable_talents_talent_id_talents_id_fk" FOREIGN KEY ("talent_id") REFERENCES "public"."talents"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "church_tradition_ranks" ADD CONSTRAINT "church_tradition_ranks_tradition_id_church_traditions_id_fk" FOREIGN KEY ("tradition_id") REFERENCES "public"."church_traditions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "church_tradition_rules" ADD CONSTRAINT "church_tradition_rules_tradition_id_church_traditions_id_fk" FOREIGN KEY ("tradition_id") REFERENCES "public"."church_traditions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "church_traditions" ADD CONSTRAINT "church_traditions_god_id_gods_id_fk" FOREIGN KEY ("god_id") REFERENCES "public"."gods"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "moral_codex_entries" ADD CONSTRAINT "moral_codex_entries_tradition_id_church_traditions_id_fk" FOREIGN KEY ("tradition_id") REFERENCES "public"."church_traditions"("id") ON DELETE cascade ON UPDATE no action;