CREATE TABLE "blessings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "blessings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"effect" text NOT NULL,
	"range" text NOT NULL,
	"duration" text NOT NULL,
	"target_category" text NOT NULL,
	"aspect" varchar(100) NOT NULL,
	"kap_cost" integer DEFAULT 1 NOT NULL,
	"ap_value" integer DEFAULT 1 NOT NULL
);
