CREATE TABLE "ceremonies" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ceremonies_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"description" text,
	"probe" varchar(100) NOT NULL,
	"modified_by_sk" integer DEFAULT 0 NOT NULL,
	"modified_by_zk" integer DEFAULT 0 NOT NULL,
	"effect" text NOT NULL,
	"ceremony_duration" varchar(100),
	"kap_cost" varchar(255),
	"costs_not_modifiable" integer DEFAULT 0 NOT NULL,
	"range" varchar(100),
	"duration" varchar(100),
	"target_category" varchar(255),
	"distribution" varchar(255),
	"improvement_factor" varchar(5)
);
