CREATE TABLE "culture_social_statuses" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "culture_social_statuses_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"culture_id" integer NOT NULL,
	"social_status_id" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "social_statuses" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "social_statuses_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"level" integer NOT NULL,
	"name" varchar(100) NOT NULL,
	"examples" text[],
	CONSTRAINT "social_statuses_level_unique" UNIQUE("level")
);
--> statement-breakpoint
ALTER TABLE "culture_social_statuses" ADD CONSTRAINT "culture_social_statuses_culture_id_cultures_id_fk" FOREIGN KEY ("culture_id") REFERENCES "public"."cultures"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "culture_social_statuses" ADD CONSTRAINT "culture_social_statuses_social_status_id_social_statuses_id_fk" FOREIGN KEY ("social_status_id") REFERENCES "public"."social_statuses"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cultures" DROP COLUMN "socialStatus";